const fortunes = [
  "Eğer bir film karakteri olsaydın, kim olurdun?",  
"Bir günlüğüne görünmez olsan ne yapardın?",  
"Hayatının bir dönemini tekrar yaşamak istesen hangisi olurdu?",  
"En son seni gerçekten şaşırtan şey neydi?",  
"Bir kitaba başlık atsaydın, ne olurdu?",  
"Zamanın herhangi bir anına seyahat edebilsen nereye giderdin?",  
"Sence sıradan bir günde gizli bir sihir olabilir mi?",  
"Uyandığında aklına gelen ilk şey genellikle nedir?",  
"Şu an hayatında neyin fazlası var?",  
"Şu an hayatında neyin eksik olduğunu düşünüyorsun?",  
"Bir sesin hayatını anlatmasını istesen kimi seçerdin?",  
"Hiç seni sen yapan bir tesadüf yaşadın mı?",  
"Kendine bir motto yazsan ne olurdu?",  
"Hangisi olmayı tercih ederdin: Cesur mu, bilge mi?",  
"Sence hayatta herkesin öğrenmesi gereken bir şey nedir?",  
"Hiç içinden bir şeyin doğru olduğunu bilip ona göre hareket ettin mi?",  
"Bir cümleyle çocukluğunu tarif etsen ne derdin?",  
"Bir film çekiyor olsan konusu ne olurdu?",  
"Gerçek hayatta sihirli bir yetenek seçme şansın olsa hangisini alırdın?",  
"En garip yeteneğin ya da becerin ne?",  
"Yolda yürürken aklına gelen en saçma düşünce neydi?",  
"Hiç aynı rüyayı tekrar tekrar gördün mü?",  
"Bir günlüğüne başka birinin yerine geçsen kimi seçerdin?",  
"Kendi hayatını anlatan bir şarkı yazılsa, adı ne olurdu?",  
"Bir sabah başka bir şehirde uyanma şansın olsa nereye gitmek isterdin?",  
"Her gün yapmaktan hoşlandığın küçük ama değerli bir alışkanlığın var mı?",  
"İnsanların seni daha çok neyle hatırlamasını isterdin?",  
"Sence seni en iyi anlatan kelime nedir?",  
"Hiç bir kelime duyduğunda anında mutlu olur musun? Hangi kelime?",  
"Çocukken inandığın ama artık saçma gelen bir şey ne?",  
"Bir şeyi sonsuza kadar yapabilsen, bu ne olurdu?",  
"Evren sana bir mesaj gönderseydi, ne yazardı?",  
"Hiçbir şey için endişelenmemen gerekse ne yapardın?",  
"Sence aşkı en iyi tanımlayan film hangisi?",  
"En çok hangi hayali gerçekleştirmek seni değiştirirdi?",  
"Geçmişte aldığın en spontan karar neydi?",  
"Bir gün boyunca sadece evet deseydin, günün nasıl geçerdi?",  
"Bir objeye dönüştürülsen, ne olmak isterdin?",  
"Bugün birine yardım edecek olsan ne yapardın?",  
"İçinde hep tutup söylemediğin ama söylemek istediğin bir şey var mı?",  
"En çok hangi durumlarda zamanın nasıl geçtiğini anlamazsın?",  
"Senin için ‘özgürlük’ ne demek?",  
"Bir roman kahramanı seni canlandırsa kimi istersin?",  
"Şu an bir kapı açılsa, nereye çıksın isterdin?",  
"Hiçbir şey düşünmeden yaptığın ama iyi ki yapmışım dediğin bir şey var mı?",  
"Hayatın bir sezona benzeseydi, hangi sezon olurdu?",  
"Bir yolculuğa çıksan, kimseye haber vermeden mi gidersin, herkesi çağırarak mı?",  
"Hayatına yön veren bir soru oldu mu?",  
"Kalabalığın içinde yalnız hissettiğin bir an oldu mu?",  
"En çok hangi müzik seni anlatıyor gibi hissettiriyor?",  
"Yıldızlara bir dilek göndersen ne dilerdin?",  
"En son seni çocuk gibi hissettiren şey neydi?",  
"Bir sabah hafızan silinse, tekrar hatırlamak isteyeceğin ilk şey ne olurdu?",  
"Bazen kendine hangi nasihati veriyorsun ama hiç tutmuyorsun?",  
"Hangi detay seni bir insana bağlar?",  
"En son hangi duyguyu gizledin?",  
"Sence insanların çoğu neyi yanlış anlıyor?",  
"Hayatın sana en büyük sürprizi neydi?",  
"Şu anda bulunduğun yer dışında nerede olsan daha mutlu olurdun?",  
"Seni ‘sen’ yapan en büyük farkın nedir?",  
"Hayat bir oyun olsaydı, senin görevin ne olurdu?",  
"Bir sabah her şeyi geride bırakma şansın olsa, yapar mısın?",  
"Bir arkadaşlıkta en çok neye değer verirsin?",  
"Şu an bir mektup yazacak olsan, kime olurdu?",  
"Hayatına film ismi koysan ne olurdu?",  
"Bir anda herkes seni dinlese, ne söylersin?",  
"Kimi ya da neyi özlüyorsun şu an?",  
"Hayatında başa sardığın bir an olsa, o anı tekrar yaşamak ister misin?",  
"Senin için huzur tam olarak nasıl bir şey?",  
"Gece sessizliğinde en çok ne düşünürsün?",  
"Hayatındaki hangi anı zaman dursa keşke derdin?",  
"Şu an içinde tuttuğun en büyük duygu ne?",  
"Hiçbir sebep olmadan gülümsediğin bir anı hatırlıyor musun?",  
"Bir hayalin gerçekleştiğinde seni en çok ne şaşırtırdı?",  
"Kendinle gurur duyduğun bir anı paylaşır mısın?",  
"Bir arkadaşının senin hakkında bilmesini istediğin bir sır ne olurdu?",  
"Hiçbir şey yapmadan saatler geçirmek seni rahatsız eder mi?",  
"Hayat bir desen olsaydı, nasıl görünürdü?",  
"Bugün kendine bir not yazsan ne yazardın?",  
"En çok hangi ortamda kendin gibi hissediyorsun?",  
"Bir şeye başlarken seni durduran ne olur genelde?",  
"Senin için ‘iyi bir gün’ nasıl geçer?",  
"Sence insan en çok ne zaman yalnız hisseder?",  
"Bir kitapta yaşamak istesen, hangi kitap olurdu?",  
"Hiç bir yabancının sana iyi geldiği bir an yaşadın mı?",  
"Bir rüyanın içine girip yaşayabilsen, hangi rüya olurdu?",  
"Hiç kimsenin görmediği bir yönünü anlatır mısın?",  
"Birini tanımak için en iyi yol nedir sence?",  
"Kendini en iyi ifade ettiğin ortam hangisi?",  
"Bir gün boyunca başka birinin iç dünyasında yaşasan kimi seçerdin?",  
"Hayatta ‘iyi ki geç kaldım’ dediğin bir olay var mı?",  
"Geçmişte seni en çok değiştiren bir cümle hatırlıyor musun?",  
"En çok neyin hayalini kurarsın ama bir türlü yapamazsın?",  
"Sence suskunluk bazen daha çok şey anlatır mı?",  
"Bir hatanı telafi etmek istesen ne olurdu?",  
"Şu an içini en çok kıpırdatan şey ne?",  
"Bir hayal kur. Sonra söyle: Gerçek olması seni korkutur muydu?",  
"Hiç kendinle gurur duyduğun ama kimseye anlatmadığın bir şey var mı?",  
"Bir rüyanın içinde kaybolsan, çıkmak ister misin?",  
"Sence bir anı, ne zaman unutulmaz olur?",  
"Geçmişteki hangi kararı değiştirmek isterdin?",  
"Bir gün bir mektup alsan ve içinde kaderin yazsa, açar mıydın?",  
"Hayatındaki hangi rastlantı seni çok etkiledi?",  
"En çok hangi durumda içinden konuşursun?",  
"Bir sabah farklı biri olarak uyansan ilk ne yaparsın?",  
"Senin için çocukluk kokusu ne demek?",  
"Kendine hiç zaman tanımadan yaptığın bir hata oldu mu?",  
"Sence hayat bazen susmak mıdır, konuşmak mı?",  
"En çok hangi film seni düşündürmüştü?",  
"Birinin hayatına girmek senin için ne kadar zor ya da kolay?",  
"Geçmişte duyduğun ama hiç unutamadığın bir söz neydi?",  
"Bir günlüğüne herkes seni dürüstçe cevaplamak zorunda kalsa ne sorardın?",  
"Hiç hayal ettiğin birini gerçekte tanıyınca hayal kırıklığına uğradın mı?",  
"Sence en zor alınan karar hangisidir?",  
"Bir duygunun rengini seçsen, hangisini hangi duyguya verirdin?",  
"İçinde kalan en büyük 'keşke' nedir?",  
"Bir zaman makinesi icat edilse ilk ne yaparsın?",  
"Bir çiçek olsaydın hangisi olurdun?",  
"Hiç kendinle savaşmak zorunda kaldığın bir an oldu mu?",  
"Bir şeyden vazgeçmek sana ne hissettirir?",  
"Şu an kalbinde bir şey taşıyorsan bu ne olurdu?",  
"En çok hangi müzik seni ağlatır?",  
"Gece uykudan önce düşündüğün en son şey genelde nedir?",  
"Bir karar almak için iç sesin mi mantığın mı ağır basar?",  
"Hiç bir şehre adım atınca 'burası benim yerim' dedin mi?",  
"Birlikte sessiz kalsak, sence o sessizlik rahat mı olurdu?",
"Birine ilk bakışta çekilmeni sağlayan şey ne oluyor?",
"Flört ederken seni en çok heyecanlandıran detay ne?",
"Biriyle bağ kurduğunu ilk ne zaman anlarsın?",
"Bir bakışın anlatabileceği en güçlü duygu sence ne?",
"Hoşlandığında kendinde ilk fark ettiğin değişiklik ne olur?",
"Birlikte kahve mi, uzun bir gece yürüyüşü mü seni daha çok yakınlaştırır?",
"Birinin sesi sende nasıl bir etki bırakmalı?",
"Sence çekim mi daha önemli, uyum mu?",
"Birine dokunmadan da yakın hissedebilir misin?",
"Flört ederken en çok hangi iltifat seni etkiler?",
"Birinin gülüşü seni kendine bağlayabilir mi?",
"İlk mesaj mı daha zor, ilk buluşma mı?",
"Sence iki insan arasındaki elektrik nasıl anlaşılır?",
"Birinin sana baktığında ne hissettirmesini isterdin?",
"Hoşlandığında bunu saklamakta mı iyisin, belli etmekte mi?",
"Birlikte gülmek mi, derin konuşmak mı seni daha çok bağlar?",
"Birinin yanında zamanın hızlanması mı yavaşlaması mı hoşuna gider?",
"Sence flörtte en çekici cesaret hangisi?",
"Birine yaklaşırken seni en çok durduran şey ne?",
"Birlikte izlenecek film mi, birlikte kaybolacak bir şehir mi?",
"Birinin sana gerçekten ilgi duyduğunu nasıl anlarsın?",
"Flört ederken en masum ama etkili hamle ne sence?",
"Birine ‘gel’ demeden onu yanında hissettirebilir misin?",
"Birinin sana attığı mesajda ilk neye bakarsın?",
"Hoşlandığında kalbin mi aklın mı daha hızlı davranır?",
"Birinin kokusu sende iz bırakır mı?",
"Birlikte susup göz göze gelmek seni gerer mi, heyecanlandırır mı?",
"Flörtte gizem mi açıklık mı seni daha çok çeker?",
"Birinin sana isminle hitap etmesi ne hissettirir?",
"Sence çekim zamanla mı oluşur, aniden mi?",
"Birlikte yapılan en basit şey hangisi sana en yakın hissettirir?",
"Birinin sana küçük bir detayla dikkat etmesi etkiler mi?",
"Flört ederken en çok hangi an kalbini hızlandırır?",
"Birinin sana ‘seni merak ediyorum’ demesi nasıl hissettirir?",
"Birlikte kahkaha atmak mı, birlikte sır paylaşmak mı?",
"Birinin sana bakışında ne ararsın?",
"Hoşlandığında ilk kimi anlatırsın?",
"Sence iki insan arasındaki mesafe nasıl kısalır?",
"Birinin seni gerçekten dinlediğini hissettiğin an ne zaman?",
"Flörtte spontane olmak mı planlı olmak mı sana daha çekici?",
"Birlikte geç saatlere kadar konuşmak mı, erken bir buluşma mı?",
"Birinin sana dokunuşu hangi durumda anlam kazanır?",
"Hoşlandığında daha cesur mu olursun, daha çekingen mi?",
"Birinin sana gülümsemesi günü değiştirebilir mi?",
"Sence flörtte en güçlü bağ nerede kurulur?",
"Birlikte susmak mı, birlikte anlatmak mı daha samimi?",
"Birinin sana ‘yanındayım’ demesi ne ifade eder?",
"Flört ederken seni en çok heyecanlandıran belirsizlik ne?",
"Birinin sana bakarken gözlerini kaçırması sence ne anlatır?",
"Birlikte yürürken el ele tutmak mı, omuz omuza yürümek mi?",
"Hoşlandığında zaman algın değişir mi?",
"Birinin sana yazma şekli ilgisini ele verir mi?",
"Flörtte küçük kıskançlıklar sence tatlı mı yorucu mu?",
"Birlikte paylaşılan bir sır bağı güçlendirir mi?",
"Birinin sana kendini özel hissettirmesi için ne yapması yeterli?",
"Hoşlandığında ses tonun değişir mi?",
"Birlikte plan yapmadan geçirilen zaman mı, planlı buluşmalar mı?",
"Birinin sana beklemediğin anda yazması ne hissettirir?",
"Flörtte en çok hangi an ‘tamam’ dedirtir?",
"Birinin sana bakarken gülümsemesini fark etmek seni etkiler mi?",
"Hoşlandığında daha çok konuşur musun, daha çok dinler misin?",
"Birlikte aynı şarkıyı sevmek bağ kurdurur mu?",
"Birinin sana yaklaşırken tereddüt etmesi ne hissettirir?",
"Flörtte ilk temas sence ne zaman olmalı?",
"Birinin seni gerçekten merak ettiğini nasıl anlarsın?",
"Hoşlandığında kalbin hangi an yakalanır?",
"Birlikte aniden gülmeye başlamak mı, derin bir bakış mı?",
"Birinin sana adın dışında bir şekilde hitap etmesi etkiler mi?",
"Flört ederken seni en çok güldüren şey ne?",
"Birinin sana bakarken rahat olması ne hissettirir?",
"Hoşlandığında mesafe mi ararsın, yakınlık mı?",
"Birlikte paylaşılan küçük anlar mı büyük jestler mi?",
"Birinin seni olduğu gibi kabul ettiğini hissetmek nasıl?",
"Flörtte en çok hangi anı hatırlarsın?",
"Birinin sana ‘iyi ki varsın’ demesi ne ifade eder?",
"Hoşlandığında kalbin mi gülümser, yüzün mü?",
"Birlikte geçirilen bir akşamın ‘iyi’ olduğunu nasıl anlarsın?",
"Birinin sana bakarken zamanı unutması sence belli olur mu?",
"Flörtte seni en çok bağlayan his hangisi?",
"Birlikte susarken bile anlaşabilmek mümkün mü?",
"Birinin sana yaklaşırken kendin olabilmesi seni etkiler mi?",
"Hoşlandığında en çok hangi an yakalanmak isterdin?"
];

const shownFortunes = new Set();

function showFortune() {
  // Tüm mesajlar gösterildiyse tekrar gösterme veya resetleme yapılabilir
  if (shownFortunes.size === fortunes.length) {
    document.getElementById("fortune-text").innerText = "Tüm mesajlar gösterildi. Sayfayı yenileyin.";
    return;
  }

  let randomIndex;
  do {
    randomIndex = Math.floor(Math.random() * fortunes.length);
  } while (shownFortunes.has(randomIndex));

  shownFortunes.add(randomIndex);
  document.getElementById("fortune-text").innerText = fortunes[randomIndex];
}

