const fortunes = [
  "Eğer bir film karakteri olsaydın, kim olurdun?",  
"Bir günlüğüne görünmez olsan ne yapardın?",  
"Hayatının bir dönemini tekrar yaşamak istesen hangisi olurdu?",  
"En son seni gerçekten şaşırtan şey neydi?",  
"Bir kitaba başlık atsaydın, ne olurdu?",  
"Zamanın herhangi bir anına seyahat edebilsen nereye giderdin?",  
"Sence sıradan bir günde gizli bir sihir olabilir mi?",  
"Uyandığında aklına gelen ilk şey genellikle nedir?",  
"Şu an hayatında neyin fazlası var?",  
"Şu an hayatında neyin eksik olduğunu düşünüyorsun?",  
"Bir sesin hayatını anlatmasını istesen kimi seçerdin?",  
"Hiç seni sen yapan bir tesadüf yaşadın mı?",  
"Kendine bir motto yazsan ne olurdu?",  
"Hangisi olmayı tercih ederdin: Cesur mu, bilge mi?",  
"Sence hayatta herkesin öğrenmesi gereken bir şey nedir?",  
"Hiç içinden bir şeyin doğru olduğunu bilip ona göre hareket ettin mi?",  
"Bir cümleyle çocukluğunu tarif etsen ne derdin?",  
"Bir film çekiyor olsan konusu ne olurdu?",  
"Gerçek hayatta sihirli bir yetenek seçme şansın olsa hangisini alırdın?",  
"En garip yeteneğin ya da becerin ne?",  
"Yolda yürürken aklına gelen en saçma düşünce neydi?",  
"Hiç aynı rüyayı tekrar tekrar gördün mü?",  
"Bir günlüğüne başka birinin yerine geçsen kimi seçerdin?",  
"Kendi hayatını anlatan bir şarkı yazılsa, adı ne olurdu?",  
"Bir sabah başka bir şehirde uyanma şansın olsa nereye gitmek isterdin?",  
"Her gün yapmaktan hoşlandığın küçük ama değerli bir alışkanlığın var mı?",  
"İnsanların seni daha çok neyle hatırlamasını isterdin?",  
"Sence seni en iyi anlatan kelime nedir?",  
"Hiç bir kelime duyduğunda anında mutlu olur musun? Hangi kelime?",  
"Çocukken inandığın ama artık saçma gelen bir şey ne?",  
"Bir şeyi sonsuza kadar yapabilsen, bu ne olurdu?",  
"Evren sana bir mesaj gönderseydi, ne yazardı?",  
"Hiçbir şey için endişelenmemen gerekse ne yapardın?",  
"Sence aşkı en iyi tanımlayan film hangisi?",  
"En çok hangi hayali gerçekleştirmek seni değiştirirdi?",  
"Geçmişte aldığın en spontan karar neydi?",  
"Bir gün boyunca sadece evet deseydin, günün nasıl geçerdi?",  
"Bir objeye dönüştürülsen, ne olmak isterdin?",  
"Bugün birine yardım edecek olsan ne yapardın?",  
"İçinde hep tutup söylemediğin ama söylemek istediğin bir şey var mı?",  
"En çok hangi durumlarda zamanın nasıl geçtiğini anlamazsın?",  
"Senin için ‘özgürlük’ ne demek?",  
"Bir roman kahramanı seni canlandırsa kimi istersin?",  
"Şu an bir kapı açılsa, nereye çıksın isterdin?",  
"Hiçbir şey düşünmeden yaptığın ama iyi ki yapmışım dediğin bir şey var mı?",  
"Hayatın bir sezona benzeseydi, hangi sezon olurdu?",  
"Bir yolculuğa çıksan, kimseye haber vermeden mi gidersin, herkesi çağırarak mı?",  
"Hayatına yön veren bir soru oldu mu?",  
"Kalabalığın içinde yalnız hissettiğin bir an oldu mu?",  
"En çok hangi müzik seni anlatıyor gibi hissettiriyor?",  
"Yıldızlara bir dilek göndersen ne dilerdin?",  
"En son seni çocuk gibi hissettiren şey neydi?",  
"Bir sabah hafızan silinse, tekrar hatırlamak isteyeceğin ilk şey ne olurdu?",  
"Bazen kendine hangi nasihati veriyorsun ama hiç tutmuyorsun?",  
"Hangi detay seni bir insana bağlar?",  
"En son hangi duyguyu gizledin?",  
"Sence insanların çoğu neyi yanlış anlıyor?",  
"Hayatın sana en büyük sürprizi neydi?",  
"Şu anda bulunduğun yer dışında nerede olsan daha mutlu olurdun?",  
"Seni ‘sen’ yapan en büyük farkın nedir?",  
"Hayat bir oyun olsaydı, senin görevin ne olurdu?",  
"Bir sabah her şeyi geride bırakma şansın olsa, yapar mısın?",  
"Bir arkadaşlıkta en çok neye değer verirsin?",  
"Şu an bir mektup yazacak olsan, kime olurdu?",  
"Hayatına film ismi koysan ne olurdu?",  
"Bir anda herkes seni dinlese, ne söylersin?",  
"Kimi ya da neyi özlüyorsun şu an?",  
"Hayatında başa sardığın bir an olsa, o anı tekrar yaşamak ister misin?",  
"Senin için huzur tam olarak nasıl bir şey?",  
"Gece sessizliğinde en çok ne düşünürsün?",  
"Hayatındaki hangi anı zaman dursa keşke derdin?",  
"Şu an içinde tuttuğun en büyük duygu ne?",  
"Hiçbir sebep olmadan gülümsediğin bir anı hatırlıyor musun?",  
"Bir hayalin gerçekleştiğinde seni en çok ne şaşırtırdı?",  
"Kendinle gurur duyduğun bir anı paylaşır mısın?",  
"Bir arkadaşının senin hakkında bilmesini istediğin bir sır ne olurdu?",  
"Hiçbir şey yapmadan saatler geçirmek seni rahatsız eder mi?",  
"Hayat bir desen olsaydı, nasıl görünürdü?",  
"Bugün kendine bir not yazsan ne yazardın?",  
"En çok hangi ortamda kendin gibi hissediyorsun?",  
"Bir şeye başlarken seni durduran ne olur genelde?",  
"Senin için ‘iyi bir gün’ nasıl geçer?",  
"Sence insan en çok ne zaman yalnız hisseder?",  
"Bir kitapta yaşamak istesen, hangi kitap olurdu?",  
"Hiç bir yabancının sana iyi geldiği bir an yaşadın mı?",  
"Bir rüyanın içine girip yaşayabilsen, hangi rüya olurdu?",  
"Hiç kimsenin görmediği bir yönünü anlatır mısın?",  
"Birini tanımak için en iyi yol nedir sence?",  
"Kendini en iyi ifade ettiğin ortam hangisi?",  
"Bir gün boyunca başka birinin iç dünyasında yaşasan kimi seçerdin?",  
"Hayatta ‘iyi ki geç kaldım’ dediğin bir olay var mı?",  
"Geçmişte seni en çok değiştiren bir cümle hatırlıyor musun?",  
"En çok neyin hayalini kurarsın ama bir türlü yapamazsın?",  
"Sence suskunluk bazen daha çok şey anlatır mı?",  
"Bir hatanı telafi etmek istesen ne olurdu?",  
"Şu an içini en çok kıpırdatan şey ne?",  
"Bir hayal kur. Sonra söyle: Gerçek olması seni korkutur muydu?",  
"Hiç kendinle gurur duyduğun ama kimseye anlatmadığın bir şey var mı?",  
"Bir rüyanın içinde kaybolsan, çıkmak ister misin?",  
"Sence bir anı, ne zaman unutulmaz olur?",  
"Geçmişteki hangi kararı değiştirmek isterdin?",  
"Bir gün bir mektup alsan ve içinde kaderin yazsa, açar mıydın?",  
"Hayatındaki hangi rastlantı seni çok etkiledi?",  
"En çok hangi durumda içinden konuşursun?",  
"Bir sabah farklı biri olarak uyansan ilk ne yaparsın?",  
"Senin için çocukluk kokusu ne demek?",  
"Kendine hiç zaman tanımadan yaptığın bir hata oldu mu?",  
"Sence hayat bazen susmak mıdır, konuşmak mı?",  
"En çok hangi film seni düşündürmüştü?",  
"Birinin hayatına girmek senin için ne kadar zor ya da kolay?",  
"Geçmişte duyduğun ama hiç unutamadığın bir söz neydi?",  
"Bir günlüğüne herkes seni dürüstçe cevaplamak zorunda kalsa ne sorardın?",  
"Hiç hayal ettiğin birini gerçekte tanıyınca hayal kırıklığına uğradın mı?",  
"Sence en zor alınan karar hangisidir?",  
"Bir duygunun rengini seçsen, hangisini hangi duyguya verirdin?",  
"İçinde kalan en büyük 'keşke' nedir?",  
"Bir zaman makinesi icat edilse ilk ne yaparsın?",  
"Bir çiçek olsaydın hangisi olurdun?",  
"Hiç kendinle savaşmak zorunda kaldığın bir an oldu mu?",  
"Bir şeyden vazgeçmek sana ne hissettirir?",  
"Şu an kalbinde bir şey taşıyorsan bu ne olurdu?",  
"En çok hangi müzik seni ağlatır?",  
"Gece uykudan önce düşündüğün en son şey genelde nedir?",  
"Bir karar almak için iç sesin mi mantığın mı ağır basar?",  
"Hiç bir şehre adım atınca 'burası benim yerim' dedin mi?",  
"Senin için ‘ev’ ne demek?",  
"Bir dostunu tarif etsen nasıl anlatırsın?",  
"En çok hangi anda zamana meydan okumak istedin?",  
"İnsanlara gösterdiğin ama aslında olmadığın bir yönün var mı?",  
"Bir duvarın dili olsa, senin hakkında ne anlatırdı?",  
"Sonsuza kadar aynı yaşta kalmak istesen hangi yaş olurdu?",  
"En çok hangi kelime seni tanımlar?",  
"Senin için bir fotoğrafın gücü nedir?",  
"En çok hangi mevsim seni anlatır?",  
"Yalnızlıkla barıştığın bir an oldu mu?",  
"Hiçbir yere ait hissetmediğin bir anı hatırlıyor musun?",  
"Bir hayal kırıklığı seni nasıl değiştirdi?",  
"İnsanları tanımakta sezgilerine güvenir misin?",  
"Kendinle geçirdiğin bir gün nasıl olurdu?",  
"Hiç içinden çıkamadığın bir düşünce döngüsü oldu mu?",  
"Zihninde yıllardır çalan bir cümle var mı?",  
"En çok hangi kitap seni içine çekti?",  
"Bir şarkı gibi hissettiren bir anın var mı?",  
"Yüzleşmekten kaçındığın bir şey varsa, ne olurdu?",  
"Senin için ‘güzel bir hayat’ ne demek?",  
"Bir cümleyle hayatını özetler misin?",  
"En çok hangi tür hikâyeler seni içine çeker?",  
"Sence insanlar iç dünyalarını neden saklar?",  
"Senin için bir yolculuğun anlamı nedir?",  
"Hiç düşünmeden 'evet' dediğin bir şey oldu mu?",  
"Bir karakter özelliğinle baş başa kalsan hangisi seni zorlar?",  
"Zor bir günün sonunda sana en iyi gelen şey nedir?",  
"Sessizliğin en çok anlam kazandığı an neydi?",  
"Hayat sana bir film gibi geliyor mu, ne tür bir film?",  
"İçinde yaşamak istemeyeceğin bir duygu hangisi olurdu?",  
"Hiçbir neden olmadan değişmeye karar verdiğin bir an oldu mu?",  
"Hiç bir bakış seni tamamen çözmüş gibi hissettirdi mi?",  
"En çok hangi tür insanlarla zaman geçirmek seni yorar?",  
"Bir yabancıyla en derin sohbete girdiğin anı hatırlıyor musun?",  
"Zihninde sık sık dönen bir soru var mı?",  
"İnsanları çeken şeyin ne olduğunu düşünüyorsun?",  
"En zor özür neydi senin için?",  
"Bir hayvanın bakışından ne anlıyorsun?",  
"Hiç hayatta yanlış anlaşıldığını düşündüğün bir an oldu mu?",  
"Sence hayat bir oyun mu, bir ders mi?",  
"En büyük suskunluğun ne anlattı?",  
"Bir insanın varlığı nasıl güç verir?",  
"Senin için unutmak mı affetmek mi daha zor?",  
"Hiç farkında olmadan biri için çok şey oldun mu?",  
"Zamanı durdurabilsen hangi anı durdururdun?",  
"İçinde yankılanan bir cümle var mı, bir şarkıdan ya da konuşmadan?",  
"Bir şeyi çok istedikten sonra onu kaybetmenin hissi sence nedir?",  
"Kendine en çok ne zaman kızarsın?",  
"Hiçbir şeyin anlamlı gelmediği anlar yaşadın mı?",  
"Bir başkasının gözünden kendini görebilsen ne görürsün?",  
"Bir yaz akşamı nereye gitmek isterdin?",  
"Hiçbir şey söylemeden çok şey anlatabildiğin biri oldu mu?",  
"Senin için en güzel sessizlik nerede yaşanır?",  
"Küçük bir iyilikle bütün günü güzelleştirdiğin bir anı var mı?",  
"Seninle aynı frekansta olduğunu düşündüğün biri oldu mu?",  
"Bir düş kırıklığını yazıya dökseydin nasıl başlardın?",  
"Şu an olduğun kişi olmana katkı sağlayan en küçük olay neydi?",  
"Bir melodinin seni çocukluğuna götürdüğü anı hatırlıyor musun?",  
"En çok hangi sokakta kendini iyi hissettin?",  
"Bir rüya, seni günlerce etkiledi mi?",  
"En derin yalnızlığın hangi şehirdeydi?",  
"Bir yabancının yaptığı en etkileyici iyilik neydi?",  
"Senin için 'güven' hangi sesle başlar?",  
"Zihninde hep aynı sahneyi oynatan bir anı var mı?",  
"Bir cümlenin seni değiştirdiğini hissettin mi?",  
"Hiçbir şey yapmadan geçirilen zaman sence boşa mıdır?",  
"Senin için ‘an’ı yakalamak ne demek?",  
"En çok hangi müzik seni yaşadığın anda tutar?",  
"Hayatın boyunca sadece bir manzaraya bakabilecek olsan hangisi olurdu?",  
"Senin için bir gülüş ne zaman samimidir?",  
"İçinde bulunduğun mekân ruh halini nasıl etkiler?"
];

const shownFortunes = new Set();

function showFortune() {
  // Tüm mesajlar gösterildiyse tekrar gösterme veya resetleme yapılabilir
  if (shownFortunes.size === fortunes.length) {
    document.getElementById("fortune-text").innerText = "Tüm mesajlar gösterildi. Sayfayı yenileyin.";
    return;
  }

  let randomIndex;
  do {
    randomIndex = Math.floor(Math.random() * fortunes.length);
  } while (shownFortunes.has(randomIndex));

  shownFortunes.add(randomIndex);
  document.getElementById("fortune-text").innerText = fortunes[randomIndex];
}
